### ISSUE TITLE
基础开发架构做得怎么样了？是否需要大家讨论？

### ISSUE THREAD

**Issue by xiaojunjerry** [JerryTeam/MyPlanFront#4]

**Comment by XiaRunxi** [comment]
我已经做好了前端的基础架构搭建，很快我会上传。另外，我看了一下目前的开发分支结构，我们分支是直接合并到master上的，为了确保master的质量，我们是否应该再建一个单独的开发merge？

**Comment by xiaojunjerry** [comment]
可以的，这样我们不直接合并到master，而是直接合并到一个叫developer这样的开发主分支上，在developer上进行测试，没有问题后，再合并到master。

**Comment by XiaRunxi** [comment]
OK,This is great。
